<?php

namespace Arakne\Tests\Spinneret\ValueObject;

use Arakne\Spinneret\ValueObject\IntegerValueObject;
use Arakne\Spinneret\ValueObject\InvalidPrimitiveTypeError;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

class IntegerValueObjectTest extends TestCase
{
    #[Test]
    public function fromSuccess()
    {
        $vo = IntegerValueObject::from(42);

        $this->assertSame(42, $vo->value());
        $this->assertSame(42, $vo->value);
        $this->assertSame('42', (string) $vo);
        $this->assertSame('42', json_encode($vo));
        $this->assertTrue($vo->equals($vo));
        $this->assertTrue($vo->equals(IntegerValueObject::from(42)));
        $this->assertFalse($vo->equals(IntegerValueObject::from(24)));
        $this->assertFalse($vo->equals(new readonly class (42) extends IntegerValueObject {
            public function __construct(int $value)
            {
                parent::__construct($value);
            }
        }));
    }

    #[Test]
    public function fromFailure()
    {
        $this->expectException(InvalidPrimitiveTypeError::class);
        $this->expectExceptionMessage('Invalid primitive type for Arakne\Spinneret\ValueObject\IntegerValueObject. Expected int, got string');
        IntegerValueObject::from('42');
    }

    #[Test]
    public function tryFrom()
    {
        $this->assertNull(IntegerValueObject::tryFrom('42'));
        $this->assertNull(IntegerValueObject::tryFrom(42.0));
        $this->assertNull(IntegerValueObject::tryFrom(null));
        $this->assertNull(IntegerValueObject::tryFrom(false));
        $this->assertEquals(IntegerValueObject::from(42), IntegerValueObject::tryFrom(42));
    }

    #[Test]
    public function withCustomConstraint()
    {
        $this->assertSame(22, TestIntWithValidation::from(22)->value);
        $this->assertSame(22, TestIntWithValidation::tryFrom(22)->value);
        $this->assertNull(TestIntWithValidation::tryFrom(21));

        try {
            TestIntWithValidation::from(21);
            $this->fail('Expected exception');
        } catch (InvalidPrimitiveTypeError $e) {
            $this->assertSame('Invalid primitive type for Arakne\Tests\Spinneret\ValueObject\TestIntWithValidation. Expected even int, got int', $e->getMessage());
        }
    }
}

readonly class TestIntWithValidation extends IntegerValueObject
{
    public static function from(mixed $value): static
    {
        if ($value % 2 !== 0) {
            throw new InvalidPrimitiveTypeError(static::class, 'even int', $value);
        }

        return parent::from($value); // TODO: Change the autogenerated stub
    }
}
