<?php

namespace Arakne\Tests\Spinneret\ValueObject;

use Arakne\Spinneret\ValueObject\InvalidValueException;
use Arakne\Spinneret\ValueObject\StringValueObject;
use Arakne\Spinneret\ValueObject\InvalidPrimitiveTypeError;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

class StringValueObjectTest extends TestCase
{
    #[Test]
    public function fromSuccess()
    {
        $vo = StringValueObject::from('foo');

        $this->assertSame('foo', $vo->value());
        $this->assertSame('foo', $vo->value);
        $this->assertSame('foo', (string) $vo);
        $this->assertSame('"foo"', json_encode($vo));
        $this->assertTrue($vo->equals($vo));
        $this->assertTrue($vo->equals(StringValueObject::from('foo')));
        $this->assertFalse($vo->equals(StringValueObject::from('bar')));
        $this->assertFalse($vo->equals(new readonly class ('foo') extends StringValueObject {
            public function __construct(string $value)
            {
                parent::__construct($value);
            }
        }));
    }

    #[Test]
    public function fromFailure()
    {
        $this->expectException(InvalidPrimitiveTypeError::class);
        $this->expectExceptionMessage('Invalid primitive type for Arakne\Spinneret\ValueObject\StringValueObject. Expected string, got int');
        StringValueObject::from(42);
    }

    #[Test]
    public function tryFrom()
    {
        $this->assertNull(StringValueObject::tryFrom(74));
        $this->assertNull(StringValueObject::tryFrom(42.0));
        $this->assertNull(StringValueObject::tryFrom(null));
        $this->assertNull(StringValueObject::tryFrom(false));
        $this->assertEquals(StringValueObject::from('foo'), StringValueObject::tryFrom('foo'));
    }

    #[Test]
    public function withCustomConstraint()
    {
        $this->assertSame('ab', TestStringWithValidation::from('ab')->value);
        $this->assertSame('ab', TestStringWithValidation::tryFrom('ab')->value);
        $this->assertNull(TestStringWithValidation::tryFrom('abc'));

        try {
            TestStringWithValidation::from('abc');
            $this->fail('Expected exception');
        } catch (InvalidValueException $e) {
            $this->assertSame('Invalid value for Arakne\Tests\Spinneret\ValueObject\TestStringWithValidation: even length', $e->getMessage());
        }
    }
}

readonly class TestStringWithValidation extends StringValueObject
{
    public static function from(mixed $value): static
    {
        if (strlen($value) % 2 !== 0) {
            throw new InvalidValueException(static::class, 'even length');
        }

        return parent::from($value); // TODO: Change the autogenerated stub
    }
}
