<?php

namespace Arakne\Tests\Spinneret\Router\Compiler;

use Arakne\Spinneret\Application\Application;
use Arakne\Spinneret\Form\FormFactoryLoader;
use Arakne\Spinneret\Router\Compiler\UrlGeneratorCompiler;
use Arakne\Spinneret\Router\RouteCollectionBuilder;
use Arakne\Spinneret\Router\UrlGenerator;
use Arakne\Spinneret\Util\Files;
use Arakne\Tests\Spinneret\Router\Fixtures\HelloRequest;
use Arakne\Tests\Spinneret\Router\Fixtures\MixedFieldsRequest;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Quatrevieux\Form\DefaultFormFactory;
use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\RouteCollection;

class UrlGeneratorCompilerTest extends TestCase
{
    private RouteCollection $routes;
    private Application $app;
    private string $cacheDir;

    protected function setUp(): void
    {
        $this->cacheDir = '/tmp/url_generator_compiler_test';
        $routesBuilder = new RouteCollectionBuilder();

        $routesBuilder->get('/hello', HelloRequest::class);
        $routesBuilder->post('/test', MixedFieldsRequest::class);

        $this->routes = $routesBuilder->routes;
        $this->app = new class($this->cacheDir) extends Application {
            public function __construct(private string $cacheDir)
            {
                parent::__construct();
            }

            public function cacheDir(): string
            {
                return $this->cacheDir;
            }
        };

        $this->clearCache();
    }

    protected function tearDown(): void
    {
        $this->clearCache();
    }

    private function clearCache(): void
    {
        Files::rmdir($this->cacheDir);
    }

    #[Test]
    public function compile()
    {
        $routes = clone $this->routes;

        $compiler = new UrlGeneratorCompiler(DefaultFormFactory::runtime());
        $compiler->compile($this->app, $this->routes);

        $this->assertEquals($routes, $this->routes);

        $this->assertFileExists($this->cacheDir . '/url_generator_routes.php');
        $this->assertEquals(<<<'PHP'
<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'Arakne\Tests\Spinneret\Router\Fixtures\HelloRequest' => [[], ['_target' => 'Arakne\\Tests\\Spinneret\\Router\\Fixtures\\HelloRequest', '_fields_extractor' => 'Arakne\\Spinneret\\Router\\Field\\FieldsExtractor'], [], [['text', '/hello']], [], [], []],
    'Arakne\Tests\Spinneret\Router\Fixtures\MixedFieldsRequest' => [[], ['_target' => 'Arakne\\Tests\\Spinneret\\Router\\Fixtures\\MixedFieldsRequest', '_fields_extractor' => 'Arakne\\Spinneret\\Router\\Field\\FieldsExtractor'], [], [['text', '/test']], [], [], []],
];

PHP
            , file_get_contents($this->cacheDir . '/url_generator_routes.php')
        );
    }

    #[Test]
    public function loadNotYetCompiled()
    {
        $compiler = new UrlGeneratorCompiler(DefaultFormFactory::runtime());
        $this->assertNull($compiler->load($this->app, new RequestContext()));
    }

    #[Test]
    public function loadCompiled()
    {
        $compiler = new UrlGeneratorCompiler(DefaultFormFactory::runtime());
        $compiler->compile($this->app, $this->routes);

        $loaded = $compiler->load($this->app, new RequestContext());

        $this->assertInstanceOf(UrlGenerator::class, $loaded);
        $this->assertSame('http://localhost/hello', $loaded->url(HelloRequest::class));
    }

    #[Test]
    public function loadCompiledInvalidFile()
    {
        $compiler = new UrlGeneratorCompiler(DefaultFormFactory::runtime());
        $compiler->compile($this->app, $this->routes);

        file_put_contents($this->cacheDir . '/url_generator_routes.php', '<?php return 42;');

        $this->assertNull($compiler->load($this->app, new RequestContext()));
    }

    #[Test]
    public function loadCompiledError()
    {
        $compiler = new UrlGeneratorCompiler(DefaultFormFactory::runtime());
        $compiler->compile($this->app, $this->routes);

        file_put_contents($this->cacheDir . '/url_generator_routes.php', '<?php syntax error!');

        $this->assertNull($compiler->load($this->app, new RequestContext()));
    }
}
