name: Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    MYSQL_TEST_HOST: '127.0.0.1'
    MYSQL_TEST_DATABASE: 'test'
    MYSQL_TEST_USER: 'root'
    MYSQL_TEST_PASSWORD: 'root'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['8.4']
        name: PHP ${{ matrix.php-versions }}

        steps:
            - uses: actions/checkout@v2

            - name: Set Timezone
              uses: szenius/set-timezone@v1.0
              with:
                  timezoneLinux: "Europe/Paris"

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: json, apcu
                  ini-values: date.timezone=Europe/Paris, apc.enabled=1, apc.enable_cli=1
            - name: Check PHP Version
              run: php -v

            - uses: mirromutth/mysql-action@v1.1
              with:
                  mysql version: '8.4'
                  mysql root password: 'root'
                  mysql database: 'test'
                  mysql user: 'test'
                  mysql password: 'test'

            - name: Install SVG renderer commands
              run: |
                  sudo apt-get update
                  sudo apt-get install -y librsvg2-bin

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Wait for MySQL
              run: |
                  while :
                  do
                    sleep 1
                    mysql -h 127.0.0.1 -u root --password=root -e 'select version()' && break
                  done

            - name: Run test suite
              run: vendor/bin/phpunit

    analysis:
        name: Analysis
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set Timezone
              uses: szenius/set-timezone@v1.0
              with:
                  timezoneLinux: "Europe/Paris"

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.4
                  extensions: json, apcu
                  ini-values: date.timezone=Europe/Paris, apc.enabled=1, apc.enable_cli=1

            - uses: mirromutth/mysql-action@v1.1
              with:
                  mysql root password: 'root'
                  mysql database: 'test'
                  mysql user: 'test'
                  mysql password: 'test'

            - name: Install SVG renderer commands
              run: |
                  sudo apt-get update
                  sudo apt-get install -y librsvg2-bin

            - name: Install Infection
              run: |
                wget https://github.com/infection/infection/releases/download/0.28.1/infection.phar
                wget https://github.com/infection/infection/releases/download/0.28.1/infection.phar.asc
                chmod +x infection.phar
                gpg --recv-keys C6D76C329EBADE2FB9C458CFC5095986493B4AA0 && gpg --with-fingerprint --verify infection.phar.asc infection.phar

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run type coverage
              run: ./vendor/bin/phpstan --no-progress

#            - name: Run type coverage (Web)
#              run: ./vendor/bin/psalm --no-cache --output-format=github -c psalm-web.xml

            - name: Run checkstyle
              run: PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer check --diff

            - name: Wait for MySQL
              run: |
                  while :
                  do
                    sleep 1
                    mysql -h 127.0.0.1 -u root --password=root -e 'select version()' && break
                  done

#            - name: Run Infection
#              run: |
#                ./infection.phar --logger-github

#    coverage:
#        name: Test coverage
#        runs-on: ubuntu-latest
#
#        steps:
#            - uses: actions/checkout@v2
#
#            - name: Set Timezone
#              uses: szenius/set-timezone@v1.0
#              with:
#                  timezoneLinux: "Europe/Paris"
#
#            - name: Install PHP
#              uses: shivammathur/setup-php@v2
#              with:
#                  php-version: 8.1
#                  extensions: json
#                  ini-values: date.timezone=Europe/Paris
#
#            - uses: mirromutth/mysql-action@v1.1
#              with:
#                  mysql version: '5.7'
#                  mysql root password: 'root'
#
#            - name: Install dependencies
#              run: composer install --prefer-dist --no-progress
#
#            - name: Run test coverage
#              run: ./vendor/bin/phpunit --coverage-clover=coverage.xml
#
#            - name: Upload coverage to Codecov
#              uses: codecov/codecov-action@v2
#              with:
#                  files: coverage.xml